name: dwell
description: What if Dart had a nice data access library?
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.8
dependencies: 
  postgres: ^2.6.3
